name: widgetbook_models
description: A starting point for Dart libraries or applications.
version: 1.0.0
# homepage: https://www.example.com
environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  freezed_annotation: ^0.14.3
dev_dependencies:
  build_runner: ^2.1.2
  freezed: ^0.14.5
  json_serializable: ^5.0.0
  very_good_analysis: ^2.3.0
